/**
 * src/services/xml/builder/company.xml.js
 *
 * Builds Tally XML requests for company operations
 */

'use strict';

/**
 * Build XML request to get list of all companies
 */
function buildCompaniesListXml() {
  return `<?xml version="1.0" encoding="utf-8"?>
<ENVELOPE>
  <HEADER>
    <VERSION>1</VERSION>
    <TALLYREQUEST>EXPORT</TALLYREQUEST>
    <TYPE>COLLECTION</TYPE>
    <ID>AllCompanies</ID>
  </HEADER>
  <BODY>
    <DESC>
      <STATICVARIABLES>
        <SVEXPORTFORMAT>$$SysName:XML</SVEXPORTFORMAT>
      </STATICVARIABLES>
      <TDL>
        <TDLMESSAGE>
          <COLLECTION NAME="AllCompanies">
            <TYPE>Company</TYPE>
            <FETCH>NAME,GUID,MAILINGNAME,ADDRESS1,ADDRESS2,ADDRESS3,ADDRESS4,ADDRESS5,ADDRESS6,STATE,COUNTRY,PINCODE,EMAIL,TELEPHONE,WEBSITE,PAN,TIN,SALESTAXNUMBER,INCOMETAXNUMBER,EXCISEREGISTRATIONNUMBER,CSTNUMBER,VATNUMBER,SERVICETAXNUMBER,INTERESTTAXNUMBER,BANKACCOUNTNUMBER,BANKNAME,BRANCHNAME,IFSCCODE,ACCOUNTTYPE,STARTDATE,FINANCIALYEARFROM,BOOKSFROMDATE,CURRENTPERIOD,ENABLED,ISEXPORTENABLED,ISVATENABLED,ISSERVICETAXENABLED,ISEXCISEENABLED,ISTCSABLED,ISCSTENABLED,ISVATAPPLICABLE,ISVATDEALER,ISVATABLED,ISVATABLED,ISVATABLED</FETCH>
          </COLLECTION>
        </TDLMESSAGE>
      </TDL>
    </DESC>
  </BODY>
</ENVELOPE>`;
}

/**
 * Build XML request to get detailed information for a single company
 */
function buildSingleCompanyXml({ companyName } = {}) {
  return `<?xml version="1.0" encoding="utf-8"?>
<ENVELOPE>
  <HEADER>
    <VERSION>1</VERSION>
    <TALLYREQUEST>EXPORT</TALLYREQUEST>
    <TYPE>COLLECTION</TYPE>
    <ID>CompanyDetails</ID>
  </HEADER>
  <BODY>
    <DESC>
      <STATICVARIABLES>
        <SVEXPORTFORMAT>$$SysName:XML</SVEXPORTFORMAT>
      </STATICVARIABLES>
      <TDL>
        <TDLMESSAGE>
          <COLLECTION NAME="CompanyDetails">
            <TYPE>Company</TYPE>
            <FETCH>NAME,GUID,MAILINGNAME,ADDRESS1,ADDRESS2,ADDRESS3,ADDRESS4,ADDRESS5,ADDRESS6,STATE,COUNTRY,PINCODE,EMAIL,TELEPHONE,WEBSITE,PAN,TIN,SALESTAXNUMBER,INCOMETAXNUMBER,EXCISEREGISTRATIONNUMBER,CSTNUMBER,VATNUMBER,SERVICETAXNUMBER,INTERESTTAXNUMBER,BANKACCOUNTNUMBER,BANKNAME,BRANCHNAME,IFSCCODE,ACCOUNTTYPE,STARTDATE,FINANCIALYEARFROM,BOOKSFROMDATE,CURRENTPERIOD,ENABLED,ISEXPORTENABLED,ISVATENABLED,ISSERVICETAXENABLED,ISEXCISEENABLED,ISTCSABLED,ISCSTENABLED,ISVATAPPLICABLE,ISVATDEALER,ISVATABLED,ISVATABLED,ISVATABLED</FETCH>
            <FILTER>NAME = "${companyName}"</FILTER>
          </COLLECTION>
        </TDLMESSAGE>
      </TDL>
    </DESC>
  </BODY>
</ENVELOPE>`;
}

module.exports = {
  buildCompaniesListXml,
  buildSingleCompanyXml,
};
